# Generated by Django 5.1.4 on 2025-01-08 16:52

import phonenumber_field.modelfields
import users.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=20, region=None, unique=True, validators=[users.validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
