# Generated by Django 5.1.4 on 2025-01-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_otp_sent',
            field=models.BooleanField(default=False, verbose_name='OTP отправлен'),
        ),
    ]
