# Generated by Django 5.1.4 on 2025-01-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_change_blog', 'Can change blog'), ('can_delete_blog', 'Can delete blog')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
